
services:

  db:
    image: postgres:16
    container_name: api_db
    restart: always

    environment:
      POSTGRES_USER: api_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: api_db_automation

    # ports:
    #   - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend

    container_name: api_backend

    restart: always

    depends_on:
      - db

    env_file:
      - ./backend/.env

    ports:
      - "8001:8000"

    volumes:
      - ./backend:/app

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: